apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pp-example-pvc
  namespace: apps
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  storageClassName: ebs-sc-immediate
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi