apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pp-front-pvc
  namespace: apps
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  storageClassName: ebs-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi